### ISSUE TITLE
SEQ UI Not found

### ISSUE THREAD

**Issue by husfuu** [alxyng/logruseq#5]
I have installed SEQ by followed this tutorial

https://hub.docker.com/r/datalust/seq

The docker container is succesfully running and there's no error in docker logs

But when I open http://localhost:5341 there's not found error on my browser

![Screenshot from 2023-08-20 11-02-08](https://github.com/alxyng/logruseq/assets/70875733/477cd422-baf2-42fb-af77-b90484074296)

Has anyone ever encountered an error like this?

**Comment by nblumhardt** [comment]
It looks as though you're browsing to the ingestion port; try port 80. HTH!

**Comment by husfuu** [comment]
> It looks as though you're browsing to the ingestion port; try port 80. HTH!

thanks!, it's solved.
